import pyautogui # type: ignore 

while True:
    menu = input("Digite o que deseja fazer:\nSoma = +\nSubtração = -\nMultiplicação = *\nDivisão = /\nSair = exit\nEscolha:")
    n1 = str(input("Digite o primeiro número: "))
    n2 = str(input("Digite o segundo número: "))
    if menu == "+":
        pyautogui.sleep(10)
        pyautogui.press('win')
        pyautogui.sleep(10)
        pyautogui.write('c')
        pyautogui.sleep(10)
        pyautogui.write('a')
        pyautogui.sleep(10)
        pyautogui.write('l')
        pyautogui.sleep(10)
        pyautogui.write('c')
        pyautogui.sleep(10)
        pyautogui.press('enter')
        pyautogui.sleep(10)
        pyautogui.press(n1)
        pyautogui.sleep(10)
        pyautogui.press('+')
        pyautogui.sleep(10)
        pyautogui.press(n2)
        pyautogui.sleep(10)
        pyautogui.press('enter')

    if menu == "-":
        pyautogui.sleep(10)
        pyautogui.press('win')
        pyautogui.sleep(10)
        pyautogui.write('c')
        pyautogui.sleep(10)
        pyautogui.write('a')
        pyautogui.sleep(10)
        pyautogui.write('l')
        pyautogui.sleep(10)
        pyautogui.write('c')
        pyautogui.sleep(10)
        pyautogui.press('enter')
        pyautogui.sleep(10)
        pyautogui.press(n1)
        pyautogui.sleep(10)
        pyautogui.press('-')
        pyautogui.sleep(10)
        pyautogui.press(n2)
        pyautogui.sleep(10)
        pyautogui.press('enter')

    if menu == "*":
        pyautogui.sleep(10)
        pyautogui.press('win')
        pyautogui.sleep(10)
        pyautogui.write('c')
        pyautogui.sleep(10)
        pyautogui.write('a')
        pyautogui.sleep(10)
        pyautogui.write('l')
        pyautogui.sleep(10)
        pyautogui.write('c')
        pyautogui.sleep(10)
        pyautogui.press('enter')
        pyautogui.sleep(10)
        pyautogui.press(n1)
        pyautogui.sleep(10)
        pyautogui.press('*')
        pyautogui.sleep(10)
        pyautogui.press(n2)
        pyautogui.sleep(10)
        pyautogui.press('enter')

    if menu == "/":
        pyautogui.sleep(10)
        pyautogui.press('win')
        pyautogui.sleep(10)
        pyautogui.write('c')
        pyautogui.sleep(10)
        pyautogui.write('a')
        pyautogui.sleep(10)
        pyautogui.write('l')
        pyautogui.sleep(10)
        pyautogui.write('c')
        pyautogui.sleep(10)
        pyautogui.press('enter')
        pyautogui.sleep(10)
        pyautogui.press(n1)
        pyautogui.sleep(10)
        pyautogui.press('divide')
        pyautogui.sleep(10)
        pyautogui.press(n2)
        pyautogui.sleep(10)
        pyautogui.press('enter')

    if menu == "exit":
        print("Finalizando...")
        break

    else:
        print("Digite um valor válido!")